openapi: 3.0.1
servers:
  - description: 'Api responsável pela autenticação de Fornecedores do Portal de compras'
    url: 'http://{serverUrl}:{serverHttpPort}/api/cmp/v1'
    variables:
      serverUrl:
        default: localhost
      serverHttpPort:
        default: '8051'
info:
  description: API para autenticação de Fornecedores do Portal de compras
  version: '1.000'
  title: Autenticação de Fornecedor
  contact:
    name: T-Talk
    url: API.Totvs.com.br
    email: comiteintegracao@totvs.com.br
  x-totvs:
    messageDocumentation:
      name: authVendor
      description: Autenticação de Fornecedor
      segment: Backoffice
    productInformation:
      - product: RM
        contact: TribeCP.Squad.ComprasFaturamento@totvs.com.br
        description: 'Entidade de Autenticação de Fornecedores do portal de compras'
paths:
  '/authVendor':
    get:
      tags:
        - Blocks
      summary: Retorna todos os fornecedores do portal de compras
      x-totvs:
        productInformation:
          - product: RM
            available: true
            note: Este verbo esta disponível com todos os parâmetros
            minimalVersion: 12.1.23
      description: Retorna todos os fornecedores do portal de compras
      operationId: getAll
      parameters:
        - $ref: 'https://raw.githubusercontent.com/totvs/ttalk-standard-message/master/jsonschema/apis/types/totvsApiTypesBase.json#/parameters/Authorization'
        - $ref: 'https://raw.githubusercontent.com/totvs/ttalk-standard-message/master/jsonschema/apis/types/totvsApiTypesBase.json#/parameters/Order'
        - $ref: 'https://raw.githubusercontent.com/totvs/ttalk-standard-message/master/jsonschema/apis/types/totvsApiTypesBase.json#/parameters/Page'
        - $ref: 'https://raw.githubusercontent.com/totvs/ttalk-standard-message/master/jsonschema/apis/types/totvsApiTypesBase.json#/parameters/PageSize'
      responses:
        '200':
          description: Operação realizada com sucesso
          content:
            application/json:
              schema:







                $schema: 'https://raw.githubusercontent.com/totvs/ttalk-standard-message/master/jsonschema/schemas/Block_1_000.json#'
info:
  description: Contrato de Mensagem Padronizada para listagem de blocos dos produtos TOTVS
  version: '1.000'
  title: Block
  contact:
    name: T-Talk
    url: API.Totvs.com.br
    email: comiteintegracao@totvs.com.br
  x-totvs:
    messageDocumentation:
      name: Block
      description: Dados do bloco do educacional
      segment: Educacional
    productInformation:
      - product: RM
        contact: TribeEdu.Squad.EduPortalMobile@totvs.com.br
        description: Blocos do Educacional
definitions:
  PagedBlock:
    type: object
    allOf:
      - $ref: 'https://raw.githubusercontent.com/totvs/ttalk-standard-message/master/jsonschema/apis/types/totvsApiTypesBase.json#/definitions/Paging'
      - type: object
        properties:
          items:
            type: array
            items:
              $ref: '#/definitions/Block'
  authVendor:
    description: Descreve o cadastro de Autenticação do Fornecedor
    properties:
      AuthVendorInternalId:
        description: Identificador único do Fornecedor
        type: string
        example: 0|C00013
        x-totvs:
          - product: RM
            note: TCAUTHFORNECEDOR.CODCOLCFO|TCAUTHFORNECEDOR.CODCFO
            required: false
            available: true
      CompanyIdVendor:
        description: Coligada do Fornecedor
        type: int
        example: 1
        x-totvs:
          - product: RM
            available: true
            required: true
            note: Coligada do Fornecedor
            field: CODCOLCFO
            type: integer
            canUpdate: false
      VendorCode:
        description: Cliente Fornecedor
        type: string
        example: 1
        x-totvs:
          - product: RM
            note: Cliente Fornecedor
            field: CODCFO
            type: string
            required: true
            available: true
            canUpdate: false
      UserName:
        description: Código de usuário do fornecedor
        type: string
        example: C001
        x-totvs:
          - product: RM
            available: true
            required: true
            note: Código de usuário do fornecedor
            field: CODUSUARIO
            type: string
      Password:
        type: string
        description: Senha de usuário do fornecedor
        x-totvs:
          - product: RM
            field: SENHA
            required: true
            note: Senha de usuário do fornecedor
            Type: string
            available: true
      ChangePassword:
        type: string
        description: Alterar password no primeiro acesso
        x-totvs:
          - product: RM
            field: TROCARSENHA
            required: true
            Type: string
            available: true









                
        '400':
          description: erro no momento da listagem dos relatórios
          content:
            application/json:
              schema:
                $ref: 'https://raw.githubusercontent.com/totvs/ttalk-standard-message/master/jsonschema/apis/types/totvsApiTypesBase.json#/definitions/ErrorModel'
    post:
      tags:
        - Blocks
      summary: Inclui o bloco passado na requisição
      description: Inclui o bloco passado na requisição
      operationId: postBlock
      x-totvs:
        productInformation:
          - product: RM
            available: true
            note: Este verbo esta disponível com todos os parâmetros
            minimalVersion: 12.1.23
      parameters:
        - $ref: '#/components/parameters/ProfessorInternalId'
        - $ref: '#/components/parameters/BuildingInternalId'
        - $ref: 'https://raw.githubusercontent.com/totvs/ttalk-standard-message/master/jsonschema/apis/types/totvsApiTypesBase.json#/parameters/Authorization'
      requestBody:
        content:
          application/json:
            schema:
              $ref: 'https://raw.githubusercontent.com/totvs/ttalk-standard-message/master/jsonschema/schemas/Block_1_000.json#/definitions/Block'
        description: Block para ser incluído
      responses:
        '200':
          description: Operação realizada com sucesso
          content:
            application/json:
              schema:
                $ref: 'https://raw.githubusercontent.com/totvs/ttalk-standard-message/master/jsonschema/schemas/Block_1_000.json#/definitions/Block'
        '400':
          description: erro no momento da inclusão
          content:
            application/json:
              schema:
                $ref: 'https://raw.githubusercontent.com/totvs/ttalk-standard-message/master/jsonschema/apis/types/totvsApiTypesBase.json#/definitions/ErrorModel'
  '/authVendor/{AuthVendorInternalId}':
    get:
      tags:
        - Blocks
      summary: Retorna detalhes do bloco educacional
      description: Retorna o bloco educacional
      operationId: getId
      x-totvs:
        productInformation:
          - product: RM
            available: true
            note: Este verbo esta disponível com todos os parâmetros
            minimalVersion: 12.1.23
      parameters:
        - $ref: '#/components/parameters/ProfessorInternalId'
        - $ref: '#/components/parameters/BuildingInternalId'
        - $ref: '#/components/parameters/InternalId'
        - $ref: 'https://raw.githubusercontent.com/totvs/ttalk-standard-message/master/jsonschema/apis/types/totvsApiTypesBase.json#/parameters/Authorization'
      responses:
        '200':
          description: Operação realizada com sucesso
          content:
            application/json:
              schema:
                $ref: 'https://raw.githubusercontent.com/totvs/ttalk-standard-message/master/jsonschema/schemas/Block_1_000.json#/definitions/Block'
        '404':
          description: Bloco não localizado na base
          content:
            application/json:
              schema:
                $ref: 'https://raw.githubusercontent.com/totvs/ttalk-standard-message/master/jsonschema/apis/types/totvsApiTypesBase.json#/definitions/ErrorModel'
    put:
      tags:
        - Blocks
      summary: Altera o bloco passado na requisição
      description: Altera o bloco passado na requisição
      operationId: putBlockId
      x-totvs:
        productInformation:
          - product: RM
            available: true
            note: Este verbo esta disponível com todos os parâmetros
            minimalVersion: 12.1.23
      parameters:
        - $ref: '#/components/parameters/ProfessorInternalId'
        - $ref: '#/components/parameters/BuildingInternalId'
        - $ref: '#/components/parameters/InternalId'
        - $ref: 'https://raw.githubusercontent.com/totvs/ttalk-standard-message/master/jsonschema/apis/types/totvsApiTypesBase.json#/parameters/Authorization'
      requestBody:
        content:
          application/json:
            schema:
              $ref: 'https://raw.githubusercontent.com/totvs/ttalk-standard-message/master/jsonschema/schemas/Block_1_000.json#/definitions/Block'
        description: Bloco para ser incluído
      responses:
        '200':
          description: Operação realizada com sucesso
          content:
            application/json:
              schema:
                $ref: 'https://raw.githubusercontent.com/totvs/ttalk-standard-message/master/jsonschema/schemas/Block_1_000.json#/definitions/Block'
        '400':
          description: erro no momento da alteração
          content:
            application/json:
              schema:
                $ref: 'https://raw.githubusercontent.com/totvs/ttalk-standard-message/master/jsonschema/apis/types/totvsApiTypesBase.json#/definitions/ErrorModel'
        '404':
          description: Bloco não localizado na base
          content:
            application/json:
              schema:
                $ref: 'https://raw.githubusercontent.com/totvs/ttalk-standard-message/master/jsonschema/apis/types/totvsApiTypesBase.json#/definitions/ErrorModel'
    delete:
      tags:
        - Blocks
      summary: Exclusão de bloco da base
      description: Exclusão de bloco da base
      operationId: DeleteBlock
      x-totvs:
        productInformation:
          - product: RM
            available: true
      parameters:
        - $ref: '#/components/parameters/ProfessorInternalId'
        - $ref: '#/components/parameters/BuildingInternalId'
        - $ref: '#/components/parameters/InternalId'
        - $ref: 'https://raw.githubusercontent.com/totvs/ttalk-standard-message/master/jsonschema/apis/types/totvsApiTypesBase.json#/parameters/Authorization'
      responses:
        '204':
          description: Bloco removido com sucesso
        '404':
          description: Bloco não encontrado
          content:
            application/json:
              schema:
                $ref: 'https://raw.githubusercontent.com/totvs/ttalk-standard-message/master/jsonschema/apis/types/totvsApiTypesBase.json#/definitions/ErrorModel'
components:
  parameters:
    AuthVendorInternalId:
      name: AuthVendorInternalId
      in: path
      required: true
      description: Identificador unico do fornecedor
      schema:
        type: string
  schemas: {}
