openapi: 3.0.1
servers:
  - description: Api responsável pela autenticação de Fornecedores do Portal de compras.
    url: 'http://{serverUrl}:{serverHttpPort}/api/cmp/v1'
    variables:
      serverUrl:
        default: localhost
      serverHttpPort:
        default: '8051'
info:
  description: API para autenticação de Fornecedores do Portal de compras.
  version: '1.000'
  title: Autenticação de Fornecedor.
  contact:
    name: T-Talk
    url: API.Totvs.com.br
    email: comiteintegracao@totvs.com.br
  x-totvs:
    messageDocumentation:
      name: vendorAuth
      description: Autenticação de Fornecedor.
      segment: Backoffice
    productInformation:
      - product: RM
        contact: TribeCP.Squad.ComprasFaturamento@totvs.com.br
        description: Entidade de Autenticação de Fornecedores do portal de compras.
paths:
  /vendorAuth:
    get:
      tags:
        - Vendor Authentication
      summary: Retorna todos os fornecedores do portal de compras.
      x-totvs:
        productInformation:
          - product: RM
            available: true
            note: Este verbo esta disponível com todos os parâmetros
            minimalVersion: 12.1.26
      description: Retorna todos os fornecedores do portal de compras
      operationId: getAll
      parameters:
        - $ref: 'https://raw.githubusercontent.com/totvs/ttalk-standard-message/master/jsonschema/apis/types/totvsApiTypesBase.json#/parameters/Authorization'
        - $ref: 'https://raw.githubusercontent.com/totvs/ttalk-standard-message/master/jsonschema/apis/types/totvsApiTypesBase.json#/parameters/Order'
        - $ref: 'https://raw.githubusercontent.com/totvs/ttalk-standard-message/master/jsonschema/apis/types/totvsApiTypesBase.json#/parameters/Page'
        - $ref: 'https://raw.githubusercontent.com/totvs/ttalk-standard-message/master/jsonschema/apis/types/totvsApiTypesBase.json#/parameters/PageSize'
      responses:
        '200':
          description: Operação realizada com sucesso
          content:
            application/json:
              schema:
                $ref: 'https://raw.githubusercontent.com/NeimarTOTVS/Teste/master/Api/Api.json#/definitions/vendorAuth'
        '400':
          description: erro no momento da listagem dos relatórios
          content:
            application/json:
              schema:
                $ref: 'https://raw.githubusercontent.com/totvs/ttalk-standard-message/master/jsonschema/apis/types/totvsApiTypesBase.json#/definitions/ErrorModel'
    post:
      tags:
        - Vendor Authentication
      summary: Inclusão de autenticação de fornecedor.
      description: Inclui uma autenticação de fornecedor para o portal de compras.
      operationId: postVendoAuth
      x-totvs:
        productInformation:
          - product: RM
            available: true
            note: Este verbo não possui parâmetros
            minimalVersion: 12.1.26
      requestBody:
        content:
          application/json:
            schema:
              $ref: 'https://raw.githubusercontent.com/NeimarTOTVS/Teste/master/Api/Api.json#/definitions/vendorAuth'
        description: Block para ser incluído
      responses:
        '200':
          description: Operação realizada com sucesso
          content:
            application/json:
              schema:
                $ref: 'https://raw.githubusercontent.com/NeimarTOTVS/Teste/master/Api/Api.json#/definitions/vendorAuth'
        '400':
          description: erro no momento da inclusão
          content:
            application/json:
              schema:
                $ref: 'https://raw.githubusercontent.com/totvs/ttalk-standard-message/master/jsonschema/apis/types/totvsApiTypesBase.json#/definitions/ErrorModel'
    put:
      tags:
        - Vendor Authentication
      summary: Altera a autenticação do fornecedor passado na requisição.
      description: Altera a autenticação do fornecedor passado na requisição.
      operationId: putBlockId
      x-totvs:
        productInformation:
          - product: RM
            available: true
            note: Este verbo esta disponível com todos os parâmetros
            minimalVersion: 12.1.26
      parameters:
        - $ref: '#/components/parameters/vendorAuthInternalId'
        - $ref: 'https://raw.githubusercontent.com/totvs/ttalk-standard-message/master/jsonschema/apis/types/totvsApiTypesBase.json#/parameters/Authorization'
      requestBody:
        content:
          application/json:
            schema:
              $ref: 'https://raw.githubusercontent.com/NeimarTOTVS/Teste/master/Api/Api.json#/definitions/vendorAuth'
        description: Autenticação do fornecedor para ser incluído
      responses:
        '200':
          description: Operação realizada com sucesso
          content:
            application/json:
              schema:
                $ref: 'https://raw.githubusercontent.com/NeimarTOTVS/Teste/master/Api/Api.json#/definitions/vendorAuth'
        '400':
          description: erro no momento da alteração
          content:
            application/json:
              schema:
                $ref: 'https://raw.githubusercontent.com/totvs/ttalk-standard-message/master/jsonschema/apis/types/totvsApiTypesBase.json#/definitions/ErrorModel'
        '404':
          description: Autenticação de fornecedor não localizada na base
          content:
            application/json:
              schema:
                $ref: 'https://raw.githubusercontent.com/totvs/ttalk-standard-message/master/jsonschema/apis/types/totvsApiTypesBase.json#/definitions/ErrorModel'
    delete:
      tags:
        - Vendor Authentication
      summary: Exclusão da autenticação do fornecedor do portal de compras.
      description: Exclusão da autenticação do fornecedor do portal de compras.
      operationId: DeleteBlock
      x-totvs:
        productInformation:
          - product: RM
            available: true
      parameters:
        - $ref: '#/components/parameters/vendorAuthInternalId'
        - $ref: 'https://raw.githubusercontent.com/totvs/ttalk-standard-message/master/jsonschema/apis/types/totvsApiTypesBase.json#/parameters/Authorization'
      responses:
        '204':
          description: Autenticação de fornecedor removida com sucesso
        '404':
          description: Autenticação de fornecedor não encontrada
          content:
            application/json:
              schema:
                $ref: 'https://raw.githubusercontent.com/totvs/ttalk-standard-message/master/jsonschema/apis/types/totvsApiTypesBase.json#/definitions/ErrorModel'
  '/vendorAuth/{vendorAuthInternalId}':
    get:
      tags:
        - Vendor Authentication
      summary: Retorna um fornecedor especifico do portal de compras.
      description: Retorna um fornecedor especifico do portal de compras.
      operationId: getId
      x-totvs:
        productInformation:
          - product: RM
            available: true
            note: Este verbo esta disponível com todos os parâmetros
            minimalVersion: 12.1.26
      parameters:
        - $ref: '#/components/parameters/vendorAuthInternalId'
        - $ref: 'https://raw.githubusercontent.com/totvs/ttalk-standard-message/master/jsonschema/apis/types/totvsApiTypesBase.json#/parameters/Authorization'
      responses:
        '200':
          description: Operação realizada com sucesso
          content:
            application/json:
              schema:
                $ref: 'https://raw.githubusercontent.com/NeimarTOTVS/Teste/master/Api/Api.json#/definitions/vendorAuth'
        '404':
          description: Fornecedor não localizado na base.
          content:
            application/json:
              schema:
                $ref: 'https://raw.githubusercontent.com/totvs/ttalk-standard-message/master/jsonschema/apis/types/totvsApiTypesBase.json#/definitions/ErrorModel'
components:
  parameters:
    vendorAuthInternalId:
      name: vendorAuthInternalId
      in: path
      required: true
      description: Identificador unico do fornecedor
      schema:
        type: string
  schemas: {}